apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: link-@github.com
    privateKeySecretRef:
      name: tlsstaging
    solvers:
    - http01:
        ingress:
          name: ingress-main