apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: link-@github.com
    privateKeySecretRef:
      name: tlssprod
    solvers:
    - http01:
        ingress:
          name: ingress-main