apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-app
  namespace: alternative-universe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-app
  template:
    metadata:
      labels:
        app: external-app
    spec:
      containers:
      - name: external-app
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: TITLE
          value: "This is the service #2"
---
apiVersion: v1
kind: Service
metadata:
  name: external-app
  namespace: alternative-universe
spec:
  type: ExternalName
  externalName: external-app.alternative-universe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: external-app